### ISSUE TITLE
Compatible with FreeCAD 0.20+

### ISSUE THREAD

**Issue by kaiwas** [ebrahimraeyat/PitchedRoof#2]
I can't get the component to work in FreeCAD versions 0.20+

The following error is displayed in the console at the moment of roof creation.

```
Traceback (most recent call last):
  File "/home/USERNAME/.local/share/FreeCAD/Mod/PitchedRoof/roof3d.py", line 84, in execute
    projection_face_points, wire_edges = extrude_pieces.create_3D_roof(base_obj, obj.angle, [], obj.angles)
  File "/home/USERNAME/.local/share/FreeCAD/Mod/PitchedRoof/extrude_pieces.py", line 81, in create_3D_roof
    edges, outer_points_edges = roof_poly.get_skeleton_lines_of_roof(wire, angles)
  File "/home/USERNAME/.local/share/FreeCAD/Mod/PitchedRoof/roof_poly.py", line 59, in get_skeleton_lines_of_roof
    skeleton = get_skeleton_of_roof(sketch)
  File "/home/USERNAME/.local/share/FreeCAD/Mod/PitchedRoof/roof_poly.py", line 19, in get_skeleton_of_roof
    skeleton = polyskel.skeletonize(poly, [])
  File "/home/USERNAME/.local/share/FreeCAD/Mod/PitchedRoof/polyskel.py", line 484, in skeletonize
    slav = _SLAV(polygon, holes)
  File "/home/USERNAME/.local/share/FreeCAD/Mod/PitchedRoof/polyskel.py", line 216, in __init__
    contours = [_normalize_contour(polygon)]
  File "/home/USERNAME/.local/share/FreeCAD/Mod/PitchedRoof/polyskel.py", line 68, in _normalize_contour
    contour = [Point2(float(x), float(y)) for (x, y) in contour]
  File "/home/USERNAME/.local/share/FreeCAD/Mod/PitchedRoof/polyskel.py", line 68, in <listcomp>
    contour = [Point2(float(x), float(y)) for (x, y) in contour]
Recompute failed!
```

**Comment by kaiwas** [comment]
Sorry to bother you!
The problem seems to be somewhere in the operating system. Checked the component on another computer (Manjaro-linux $ Windows 7) - everything works fine.
I will try to find the cause of the problem on my side.

**Comment by ebrahimraeyat** [comment]
Hello @kaiwas . I will investigate it in recent weeks. If I forget, please remind me. Thanks.

**Comment by kaiwas** [comment]
UPD.

It seems that everything works as it should. But for this line, the bases need to be built clockwise.
And I'm so used to building them counterclockwise that I couldn't do it for a long time ))))

**Comment by ebrahimraeyat** [comment]
You mean it must work for clockwise and counterclockwise? I think I can do it.

**Comment by kaiwas** [comment]
> You mean it must work for clockwise and counterclockwise?

This would be a great solution.
The construction in one direction is not obvious and there is no clue that it should be done clockwise. I couldn't figure out what was going on for a long time.

Thank you! Your component is much more convenient than the current version of pitched roofs that is currently in freecad.

**Comment by kaiwas** [comment]
Another possible idea for improvement is to stabilize roofs built as a rectangle. Now this also causes an error. The sketch has to be built with separate lines.


https://github.com/user-attachments/assets/2a0ad154-635f-4acf-8f17-a841b2ebf7a1

**Comment by kaiwas** [comment]
It looks like things won't get off the ground and the addon will remain a draft forever.

**Comment by ebrahimraeyat** [comment]
I am so sorry, I am very busy nowadays, it was a paid project and during the corona canceled.

**Comment by ebrahimraeyat** [comment]
I am healthy, but the job canceled because of corona!

I will be happy if I can help. I will try to look it at soon.

**Comment by ebrahimraeyat** [comment]
is this error still remain?
